vich_uploader:
    db_driver: orm

    mappings:
        product_image:
            uri_prefix: assets/img/avatar
            upload_destination: '%kernel.project_dir%/public/assets/img/avatar'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
